### ISSUE TITLE
Add more features to the app

### ISSUE THREAD

**Issue by ashegh8** [riedayme/InstaStoryDownloader#1]
**Sorry I opened a issue**
Is it possible to **add post viewing** and **downloading** to this app with a cookie?
Is it possible to save the **cookie** in the file instead of requesting it on the site?
Thanks
Sincerely

**Comment by riedayme** [comment]
for add post viewing and downloading it possible but must add other code

for save cookie in file it possible but must have a validate when cookie expired

but for now i will not change this app , thankyou

**Comment by ashegh8** [comment]
Hello,
I would be very grateful if you could add posts and download to the program
as an update to the downloader story github app.
I am waiting for the program update, dear friend
With best wishes
